# Generated by Django 4.1.7 on 2023-06-20 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_brand'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='product',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
