# Generated by Django 4.1.7 on 2023-07-30 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomDesignedorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ImageField(upload_to='')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
